import { AiFillStar } from "react-icons/ai";

const data4 = [
  {
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    title: "Flat Slip On Pumps",
    star: <AiFillStar className="rating-star" />,
    reviews: "(87 reviews)",
    prevPrice: "$140.00",
    newPrice: "119",
    company: "Vans",
    color: "green",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Knit Ballet Flat",
    star: <AiFillStar className="rating-star" />,
    reviews: "(234 reviews)",
    prevPrice: "$140.00",
    newPrice: "79",
    company: "Adidas",
    color: "black",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    star: <AiFillStar className="rating-star" />,
    reviews: "(98 reviews)",
    prevPrice: "$140.00",
    newPrice: "69",
    company: "Vans",
    color: "white",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    star: <AiFillStar className="rating-star" />,
    reviews: "(142 reviews)",
    prevPrice: "$140.00",
    newPrice: "179",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(201 reviews)",
    prevPrice: "$140.00",
    newPrice: "139",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    star: <AiFillStar className="rating-star" />,
    reviews: "(176 reviews)",
    prevPrice: "$140.00",
    newPrice: "129",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },
];

export default data4;
